<<<<<<< Updated upstream
spring.profiles.active=dev
=======
<<<<<<< HEAD
spring.application.name=job
>>>>>>> Stashed changes

spring.application.name=Jobsphere-Post

server.port=${PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

<<<<<<< Updated upstream
#logging.level.root=warn
=======
# Logging
# logging.level.root=debug
=======
spring.profiles.active=dev

spring.application.name=Jobsphere-Post

server.port=${PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

#logging.level.root=warn
>>>>>>> origin/main
>>>>>>> Stashed changes

# Optional: Show SQL queries in the console (for debugging purposes)
spring.jpa.show-sql=true

# JPA/Hibernate settings
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
<<<<<<< Updated upstream
spring.jpa.properties.hibernate.transaction.jta.platform=none
=======
<<<<<<< HEAD
spring.jpa.properties.hibernate.transaction.jta.platform=none
=======
spring.jpa.properties.hibernate.transaction.jta.platform=none
>>>>>>> origin/main
>>>>>>> Stashed changes
